import type { Badge } from "@/types";

export const BADGES: Badge[] = [
  {
    id: "first-step",
    name: "First Step",
    description: "Made it through your first day.",
    daysRequired: 1,
    accent: "bg-secondary",
  },
  {
    id: "rising-quitter",
    name: "Rising Quitter",
    description: "Three days without smoking.",
    daysRequired: 3,
    accent: "bg-secondary",
  },
  {
    id: "craving-crusher",
    name: "Craving Crusher",
    description: "Seven smoke-free days.",
    daysRequired: 7,
    accent: "bg-primary",
  },
  {
    id: "two-weeks-free",
    name: "Two Weeks Free",
    description: "Two weeks of progress.",
    daysRequired: 14,
    accent: "bg-primary",
  },
  {
    id: "top-rated",
    name: "Top Rated Quitter",
    description: "A full month smoke-free.",
    daysRequired: 30,
    accent: "bg-accent",
  },
  {
    id: "top-rated-plus",
    name: "Top Rated Plus Quitter",
    description: "Two months of consistency.",
    daysRequired: 60,
    accent: "bg-accent",
  },
  {
    id: "champion",
    name: "Champion",
    description: "Ninety days of freedom.",
    daysRequired: 90,
    accent: "bg-primary",
    premium: true,
  },
  {
    id: "half-year-hero",
    name: "Half Year Hero",
    description: "Six months smoke-free.",
    daysRequired: 180,
    accent: "bg-accent",
    premium: true,
  },
  {
    id: "year-free",
    name: "Year Free",
    description: "A full year without smoking.",
    daysRequired: 365,
    accent: "bg-accent",
    premium: true,
  },
  {
    id: "unstoppable",
    name: "Unstoppable",
    description: "Five hundred days smoke-free.",
    daysRequired: 500,
    accent: "bg-primary",
    premium: true,
  },
  {
    id: "two-year-free",
    name: "Two Year Free",
    description: "Two full years without a cigarette.",
    daysRequired: 730,
    accent: "bg-secondary",
    premium: true,
  },
  {
    id: "thousand-day-legend",
    name: "Thousand Day Legend",
    description: "One thousand days of freedom.",
    daysRequired: 1000,
    accent: "bg-accent",
    premium: true,
  },
];
