/** Motivation lines shown in the craving-session speech bubble above the avatar. */
export const CRAVING_MOTIVATION_MESSAGES = [
  "This craving will pass, whether you smoke or not. Let it pass.",
  "You don't need a cigarette right now. You need a few more minutes.",
  "Every craving you beat makes the next one easier.",
  "The urge is temporary. Your progress is permanent.",
  "You've already survived every craving so far. This one is no different.",
  "A cigarette won't solve what's bothering you.",
  "Remember why you started. Your future self is counting on you.",
  "Cravings are a sign of healing, not a sign to give up.",
  "Stay with the discomfort. It won't last forever.",
  "You are stronger than a chemical addiction.",
  "Don't trade your progress for a few minutes of relief.",
  "The craving is loud, but it doesn't control you.",
  "One cigarette is never just one cigarette.",
  "You quit for a reason. That reason still matters.",
  "Freedom begins with moments exactly like this one.",
  "The urge will fade. Your pride will remain.",
  "Take it one craving at a time, not one year at a time.",
  "You're not missing out on smoking. You're gaining your life back.",
  "Your brain is asking for nicotine. You don't have to say yes.",
  "A craving is a visitor. You don't have to invite it in.",
  "The strongest part of you made the decision to quit.",
  "You've come too far to start over today.",
  "This feeling is temporary. Your health is forever.",
  "Cravings peak and fade. Stay the course.",
  "The cigarette isn't the reward. Freedom is.",
  "Imagine how proud you'll feel in 10 minutes.",
  "Don't let a moment decide your future.",
  "The urge is uncomfortable, not dangerous.",
  "Keep your streak alive. It's worth protecting.",
  "Your lungs are thanking you right now.",
  "This is how victories are built: one craving at a time.",
  "Nicotine wants attention. Don't give it any.",
  "You're becoming the person you wanted to be.",
  "The craving is passing through. Let it keep moving.",
  "Quitting isn't easy, but it's absolutely worth it.",
  "You are reclaiming control with every minute that passes.",
  "The best response to a craving is patience.",
  "The version of you that never gives up is winning.",
  "Breathe. Wait. Watch the craving lose its power.",
  "Your future is worth more than this urge.",
  "You're proving to yourself that you can do hard things.",
  "This craving doesn't define you.",
  "You don't need nicotine to get through today.",
  "Healing often feels uncomfortable. Keep going.",
  "Every craving resisted is evidence of your strength.",
  "You're not fighting forever. You're fighting for a few minutes.",
  "Trust the process. Thousands have done it, and so can you.",
  "This moment is an opportunity to choose yourself.",
  "The craving is temporary. Your freedom is lasting.",
  "Hold on. In a few minutes, you'll be glad you did.",
] as const;

export function pickCravingMotivationMessage(): string {
  const index = Math.floor(Math.random() * CRAVING_MOTIVATION_MESSAGES.length);
  return CRAVING_MOTIVATION_MESSAGES[index] ?? CRAVING_MOTIVATION_MESSAGES[0];
}
